module.exports = {
  DATA_STORAGE_KEY: ".data",

  CONFING_STORAGE_KEY: "config",

  GIT_NAME: "tv-player/box-source",

  SITE_LIST: "site_list",

  SYNC_FILE_LIST: "SYNC_FILE_LIST",

  SETTING_DIR: "./SOURCES",
  SETTING_PATH: "SOURCES/",

  SETTING_NEW_DIR: "./SOURCES",
  SETTING_NEW_PATH: "SOURCES/",

  JAR_DIR: "./SOURCES/JAR",
  JAR_PATH: "SOURCES/JAR/",

  EXT_DIR: "./SOURCES/EXT",
  EXT_PATH: "SOURCES/EXT/",
};
